# Generated by Django 3.1.5 on 2021-01-29 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='advertisement')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='The title of ball product')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products', verbose_name='Image of product')),
                ('price', models.FloatField(verbose_name='The cost of one ball')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='The name of ball maker company')),
                ('link', models.URLField(verbose_name='Link to the maker site')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='The name of material')),
            ],
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='The name of sport')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rate', models.IntegerField(verbose_name='Rate to product got from feedback author')),
                ('photos', models.ImageField(upload_to='feedbacks', verbose_name='Review photo of product')),
                ('creation_datetime', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Feedback got by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ball', verbose_name='Reviewed product')),
            ],
        ),
        migrations.AddField(
            model_name='ball',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.manufacturer', verbose_name='Ball made by'),
        ),
        migrations.AddField(
            model_name='ball',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.material', verbose_name='Ball made of'),
        ),
        migrations.AddField(
            model_name='ball',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.sporttype', verbose_name='Sport ball made for'),
        ),
    ]
