# Generated by Django 3.1.5 on 2021-01-30 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 12, 30, 37, 931576)),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='order.ProductInCart', verbose_name='List of purchased products'),
        ),
    ]
