# Generated by Django 3.1.5 on 2021-01-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210130_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='flat',
            new_name='office',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='postcode',
        ),
    ]
