# Generated by Django 3.1.5 on 2021-01-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210130_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creation_time',
            new_name='creation_datetime',
        ),
    ]
